In [2]:
# Import Modules
import numpy as np
import pandas as pd
import os
import ta

In [3]:
from os import listdir
from os.path import isfile, join
from tqdm import tqdm

In [4]:
mypath = "./cnn_input/stocks_kaggle"
onlyfiles = sorted(listdir(mypath))

In [5]:
input_df = pd.DataFrame(columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'OpenInt', 'rsi',
                                   'rsi_signal', 'bb_upper', 'bb_mid', 'bb_lower', 'aroonup', 'aroondown',
                                   'aroon_sig', 'AB_Middle_Band', 'AB_Upper_Band', 'AB_Lower_Band',
                                   'abbands_sig', 'stoch_k', 'stoch_d', 'stoch_signal', 'CMF', 'CMF_signal', 'ROC', 
                                   'ROC_signal', 'Momentum', 'mom_signal', 'CCI', 'cci_sig', 'OBV', 'obv_signal','Keltner',
                                  'EMA', 'ATR','Norm_ATR','Movement_Index' ])

In [6]:
##merging files in one df

for file in tqdm(onlyfiles[:150]):
    print(file)
    filesize = os.path.getsize(f'{mypath}/{file}')
    
    if filesize == 0:
        pass
    else:
        price_data = pd.read_csv(f'{mypath}/{file}')
        input_df = pd.concat([input_df, price_data])
        print(len(input_df))

0it [00:00, ?it/s]

In [8]:
price_data = input_df

In [38]:
price_data = pd.read_csv('./InputData/WDI.F.csv')
price_data['Date'] = pd.to_datetime(price_data['Date'])
price_data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-01-02,133.199997,136.500000,132.050003,136.000000,135.823837,6589
1,2019-01-03,133.500000,134.149994,126.750000,127.250000,127.085167,11750
2,2019-01-04,128.800003,133.600006,128.800003,133.250000,133.077393,3678
3,2019-01-07,134.850006,137.500000,134.449997,137.149994,136.972336,5149
4,2019-01-08,135.899994,139.350006,134.350006,138.800003,138.620209,4389
5,2019-01-09,139.300003,145.199997,138.949997,144.000000,143.813477,9975
6,2019-01-10,141.500000,142.449997,139.000000,141.750000,141.566391,4389
7,2019-01-11,142.949997,143.000000,139.500000,140.449997,140.268066,4934
8,2019-01-14,138.850006,139.000000,135.399994,136.850006,136.672745,3480
9,2019-01-15,137.550003,139.100006,135.949997,138.350006,138.170792,2822
10,2019-01-16,138.300003,140.600006,137.300003,139.250000,139.069626,1694
11,2019-01-17,139.000000,144.149994,138.300003,143.600006,143.414001,5613
12,2019-01-18,145.000000,151.250000,144.300003,150.149994,149.955505,11328
13,2019-01-21,151.000000,157.399994,150.250000,155.949997,155.747986,13859
14,2019-01-22,154.850006,157.699997,153.800003,155.050003,154.849167,11748
15,2019-01-23,156.500000,160.500000,155.350006,159.699997,159.493134,7949
16,2019-01-24,161.500000,167.800003,160.649994,167.800003,167.582642,8177
17,2019-01-25,168.300003,170.199997,164.199997,166.500000,166.284332,17937
18,2019-01-28,166.899994,170.199997,165.500000,166.500000,166.284332,6276
19,2019-01-29,167.949997,167.949997,164.850006,167.399994,167.183151,6642
20,2019-01-30,166.800003,168.500000,130.000000,149.100006,148.906876,63537
21,2019-01-31,151.300003,151.300003,143.050003,145.449997,145.261597,25115
22,2019-02-01,145.500000,151.000000,101.500000,114.800003,114.651299,128455
23,2019-02-04,126.500000,133.050003,115.750000,125.849998,125.686981,226422
24,2019-02-05,128.000000,133.350006,124.650002,132.850006,132.677917,41298
25,2019-02-06,134.000000,136.600006,124.250000,130.350006,130.181168,37193
26,2019-02-07,130.500000,130.500000,105.000000,114.849998,114.701233,92993
27,2019-02-08,113.400002,117.650002,86.300003,94.959999,94.836998,164250
28,2019-02-11,97.000000,104.449997,95.919998,103.400002,103.266068,78538
29,2019-02-12,104.300003,107.599998,95.599998,102.000000,101.867874,52228
30,2019-02-13,100.750000,101.500000,95.500000,100.599998,100.469688,49640
31,2019-02-14,103.400002,106.599998,99.019997,102.300003,102.167488,34658
32,2019-02-15,102.000000,103.000000,98.820000,99.900002,99.770599,19381
33,2019-02-18,106.000000,116.199997,104.000000,115.800003,115.650002,55639
34,2019-02-19,117.000000,125.800003,116.800003,121.449997,121.292679,60079
35,2019-02-20,123.099998,123.699997,113.199997,114.250000,114.102005,43942
36,2019-02-21,114.250000,115.550003,106.849998,111.500000,111.355568,40334
37,2019-02-22,114.300003,115.800003,111.750000,115.550003,115.400330,18809
38,2019-02-25,117.050003,120.000000,114.750000,117.050003,116.898384,19693
39,2019-02-26,116.900002,118.099998,114.199997,117.000000,116.848450,6147
40,2019-02-27,117.800003,118.050003,116.400002,117.900002,117.747284,7666
41,2019-02-28,116.699997,120.349998,116.500000,120.250000,120.094238,8688
42,2019-03-01,121.000000,121.750000,118.500000,120.449997,120.293976,17122

In [10]:
"""price_data = pd.read_csv('./InputData/dax_hourly.csv',sep=',')
price_data['Timestamp'] = pd.to_datetime(price_data['Timestamp'])
price_data"""

"price_data = pd.read_csv('./InputData/dax_hourly.csv',sep=',')\nprice_data['Timestamp'] = pd.to_datetime(price_data['Timestamp'])\nprice_data"

In [11]:
"""price_data = price_data.iloc[:, :2]
price_data.columns = ['Date', 'Close']
price_data.head()"""

"price_data = price_data.iloc[:, :2]\nprice_data.columns = ['Date', 'Close']\nprice_data.head()"

In [39]:
#define function to create low & high column (if not available)
def highlow (df, close='Close'):
    price_std = df[close].std()
    df['high'] = df[close] + price_std * .2
    df['low'] = df[close] - price_std *.2
    return df
#price_data = highlow(price_data)

In [40]:
"""
price_data = pd.read_csv('./InputData/WDI.F.csv')
price_data['Date'] = pd.to_datetime(price_data['Date'])
price_data.head()
"""

"\nprice_data = pd.read_csv('./InputData/WDI.F.csv')\nprice_data['Date'] = pd.to_datetime(price_data['Date'])\nprice_data.head()\n"

In [41]:
#### RSI - Relative Strength Index ####
def rsi(price_data, price_index, lookback=14):
    
    def rsi_inner(data):   
        gain = data[data>0].mean()
        loss = -1*data[data<0].mean()    
        return 100 * gain / (gain + loss)
    
    price_data['return'] = ((price_data.iloc[:, price_index] / price_data.iloc[:, price_index].shift(1)) -1).fillna(0)
    price_data['rsi'] = price_data['return'].rolling(center=False, window=lookback).apply(rsi_inner).fillna(0)
    
    #defining buy and sell signal threshold
    rsi_buy = 30
    rsi_sell = 70
    
    #apply signals as additional feature
    price_data['rsi_signal'] = 0 #neutral signal
    price_data.loc[price_data['rsi'] < rsi_buy , 'rsi_signal'] = 1 #buy signal
    price_data.loc[price_data['rsi'] > rsi_sell , 'rsi_signal'] = -1 #sell signal
    
    price_data.drop(['return'], axis=1, inplace=True)
    return price_data

#price_data = rsi(price_data, price_index = 2)
price_data = rsi(price_data, price_index = 2)

/Users/matthewreuvers/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  # Remove the CWD from sys.path while we load stuff.

In [42]:
#### Bollinger Bands ####
def bbands(data, price_index, length=30, numsd=2):
    """ returns average, upper band, and lower band"""
    #ave = pd.stats.moments.rolling_mean(price,length)
    ave = data.iloc[:, price_index].rolling(window = length, center = False).mean()
    #sd = pd.stats.moments.rolling_std(price,length)
    sd = data.iloc[:, price_index].rolling(window = length, center = False).std()
    upband = ave + (sd*numsd)
    dnband = ave - (sd*numsd)
    
    data['bb_upper'] = np.round(upband,3)
    data['bb_mid'] = np.round(ave,3)
    data['bb_lower'] = np.round(dnband,3)
    return data

price_data = bbands(price_data, 2)

In [43]:
#### Volume (Plain) ####
def volume (data):
    data['Volume'].fillna(0)
    return data

price_data = volume(price_data)

In [44]:
#### Aroon Oscillator ####
def aroon(df, tf=25, high='High', low='Low'):
    aroonup = []
    aroondown = []
    x = tf
    
    #fill up dataframe with 0 for values below time threshold
    aroonup = [0] * tf
    aroondown = [0] * tf
        
    while x < len(df['Date']):
        aroon_up = ((df[high][x-tf:x].tolist().index(max(df[high][x-tf:x])))/float(tf))*100
        aroon_down = ((df[low][x-tf:x].tolist().index(min(df[low][x-tf:x])))/float(tf))*100
        aroonup.append(aroon_up)
        aroondown.append(aroon_down)
        x+=1
    
    df['aroonup'] = aroonup
    df['aroondown'] = aroondown
    
    ##Implement Trading Signals
    #When the Aroon Up is above the Aroon Down, it indicates bullish price behavior.
    #When the Aroon Down is above the Aroon Up, it signals bearish price behavior.
    df['aroon_sig'] = 0 
    df.loc[df['aroonup'] > df['aroondown'], 'aroon_sig'] = 1 #buy signal
    df.loc[df['aroondown'] > df['aroonup'], 'aroon_sig'] = -1
    return df


#price_data = pd.read_csv('./cnn_input/stocks_kaggle/abio.us.txt')
#price_data = aroon(price_data)
price_data = aroon(price_data, high='High', low='Low')

In [45]:
#### Price-Volume-Trend-Indicator ####
def pvt(data, signal_len = 14):
    data['momentum'] = (data['Close'] - data['Close'].shift(1)).fillna(0)
    data["PVT"] = (data['momentum'] / data['Close'].shift(1))*data['Volume']
    data["PVT"] = data["PVT"]-data["PVT"].shift(1)
    data["PVT"] = data["PVT"].fillna(0)
    
    ##Implement Trading Signals
    data['pvt_movmean'] = data['PVT'].rolling(signal_len).mean() #signal line as moving average 
    data['pvt_signal'] = 0
    data.loc[data['PVT'] > data['pvt_movmean'], 'pvt_signal'] = 1 #buy signal
    data.loc[data['PVT'] < data['pvt_movmean'], 'pvt_signal'] = -1 #sell signal
    
    data.drop(['momentum'], axis = 1, inplace = True)
    return data

#price_data = pvt(price_data)

In [46]:
#### Acceleration Bands ####
def abands(df, window = 20, high='High', low='Low'):
    
    df['AB_Middle_Band'] = df['Close'].rolling(window = window, center=False).mean()
    
    # High * ( 1 + 4 * (High - Low) / (High + Low))
    df['aupband'] = df[high] * (1 + 4 * (df[high]-df[low])/(df[high]+df[low]))
    df['AB_Upper_Band'] = df['aupband'].rolling(window=window, center=False).mean()
        
    # Low *(1 - 4 * (High - Low)/ (High + Low))
    df['adownband'] = df[low] * (1 - 4 * (df[high]-df[low])/(df[high]+df[low]))
    df['AB_Lower_Band'] = df['adownband'].rolling(window=window, center=False).mean()
    
    ##Implement Trading Signals
    df['abbands_sig'] = 0
    df.loc[df[high] > df['AB_Upper_Band'], 'abbands_sig'] = 1 #buy signal
    df.loc[df[low] > df['AB_Lower_Band'], 'abbands_sig'] = -1 #sell signal 
    
    df.drop(['adownband', 'aupband'], axis = 1, inplace = True) 
    return df
    
price_data = abands(price_data, high='High', low='Low')

In [47]:
#### Stochastic ####

def stochastic (price_data):
    
    # Creating %k 
    price_data['stoch_k'] = ta.momentum.stoch(high = price_data['High'], low = price_data['Low'], 
                                                 close = price_data['Close'], n=14, d_n=3, fillna=False)
    
    # Creating %d
    price_data['stoch_d'] = ta.momentum.stoch_signal(high = price_data['High'], low = price_data['Low'], 
                                                 close = price_data['Close'], n=14, d_n=3, fillna=False)
    
    # Setting the stoch_signal to 0 for neutral indication
    price_data['stoch_signal'] = 0
    
    # If stoch_k or stoch_d is over 80, then there is a signal to sell (overbought conditions)
    # So when either is over 80, and then stoch_k crosses stoch_d from below, then sell  -1
    price_data.loc[((price_data['stoch_k'] < price_data['stoch_d']) & (price_data['stoch_k'].shift(1) > price_data['stoch_d'].shift(1))) & (price_data['stoch_d'] > 80), 'stoch_signal'] = '-1'
    
    # If stoch_k or stoch_d is less than 20, then there is a signal to buy
    # So when either is less than 20, and then stoch_k crosses stoch_d from above, then buy  1
    price_data.loc[((price_data['stoch_k'] > price_data['stoch_d']) & (price_data['stoch_k'].shift(1) < price_data['stoch_d'].shift(1))) & (price_data['stoch_d'] < 20), 'stoch_signal'] = '1'  
    
    # Drop stoch_k and stoch_d
    #price_data  = price_data.drop(['stoch_k', 'stoch_d'], axis=1)
    
    # Making stoch_signal numeric
    price_data['stoch_signal'] = pd.to_numeric(price_data['stoch_signal'])
    
    return price_data

price_data = stochastic(price_data)

In [48]:
#### Chaikin Money Flow ####

def chaikin_money_flow (price_data):
    
    # n = 20 days as the standard
    price_data['CMF'] = ta.volume.chaikin_money_flow(high = price_data['High'], low = price_data['Low'], 
                                                                close = price_data['Close'], 
                                                                volume = price_data['Volume'], n = 20)
    # Buy & sell signals
    signs = np.sign(price_data.CMF)
    price_data['CMF_signal'] = np.sign(signs.diff()).fillna(0)

    # Making CMF_signal numeric
    price_data['CMF_signal'] = pd.to_numeric(price_data['CMF_signal'])
    
    return price_data

price_data = chaikin_money_flow(price_data)

In [49]:
#### Rate of Change ####

def rate_of_change(price_data, n = 9):
    
    """
    :param price_data: pandas.DataFrame
    :param n: 9,14,25 days common for short term traders
    :return: pandas.DataFrame
    :sell signal: from positive to negative 
    "buy signal: from negative to postive"
    """
    
    M = price_data['Close'].diff(n - 1)
    N = price_data['Close'].shift(n - 1)
    ROC = pd.Series(M / N, name='ROC')
    price_data['ROC'] = ROC
    
    # Buy & sell signals
    signs = np.sign(price_data.ROC)
    price_data['ROC_signal'] = np.sign(signs.diff()).fillna(0)
    
    # Making ROC_signal numeric
    price_data['ROC_signal'] = pd.to_numeric(price_data['ROC_signal'])
    
    return price_data

price_data = rate_of_change(price_data)

In [50]:
#### Momentum ####

def momentum(price_data, n = 10):
    '''
    
    :param df: pandas.DataFrame 
    :param n: 10 days is the standard
    :return: pandas.DataFrame
    :buy when goes from negative to positive
    :sell when goes from positive to negative
    :or 
    :buy when the momentum indicator crosses above the moving average from below
    :sell when the momentum indicator crosses below the moving average from above
    '''
    
    M = pd.Series(price_data['Close'].diff(n), name='Momentum')
    price_data['momentum'] = M
    
    # Buy & sell signals
    signs = np.sign(price_data.Momentum)
    price_data['mom_signal'] = np.sign(signs.diff()).fillna(0)
    
    # Making mom_signal numeric
    price_data['mom_signal'] = pd.to_numeric(price_data['mom_signal'])
    
    
    return price_data


price_data = momentum(price_data)

AttributeError: 'DataFrame' object has no attribute 'Momentum'

In [51]:
#### Commodity Channel Index####
def CCI(data, ndays=14): 
    TP = (data['High'] + data['Low'] + data['Close']) / 3 
    CCI = pd.Series((TP - TP.rolling(ndays).mean()) / (0.015*TP.rolling(ndays).std()),
                    name = 'CCI') 
    
    data['CCI'] = CCI
    #defining buy and sell signal threshold
    cci_buy = 100
    cci_sell = -100
    #apply signals as additional feature
    data['cci_sig'] = 0 #neutral signal
    data.loc[data['CCI' ] > cci_buy , 'cci_sig'] = 1 #buy signal
    data.loc[data['CCI'] < cci_sell , 'cci_sig'] = -1 #sell signal
    
    return data

price_data = CCI(price_data)

In [52]:
### On Balance Volume ###

def on_balance_volume(df, n=14):
    i = 0
    OBV = [0]
    while i < df.index[-1]:
        if df.loc[i + 1, 'Close'] - df.loc[i, 'Close'] > 0:
            OBV.append(df.loc[i + 1, 'Volume'])
        if df.loc[i + 1, 'Close'] - df.loc[i, 'Close'] == 0:
            OBV.append(0)
        if df.loc[i + 1, 'Close'] - df.loc[i, 'Close'] < 0:
            OBV.append(-df.loc[i + 1, 'Volume'])
        i = i + 1
    OBV = pd.Series(OBV)
    OBV_ma = pd.Series(OBV.rolling(n, min_periods=n).mean(), name='OBV')
    
    df['OBV'] = OBV
    df['OBV_ma'] = OBV_ma
    
    #adding signal conditions
    price_data['Price P/N'] = (price_data['Close'].diff().bfill() > 0).astype(int)
    price_data['OBV P/N'] = (price_data['OBV'].diff().bfill() > 0).astype(int)
    #signal
    price_data['obv_signal'] = 0 #neutral signal
    price_data.loc[price_data['OBV P/N' ]  > price_data['Price P/N'], 'obv_signal'] = 1 #buy signal
    price_data.loc[price_data['OBV P/N' ] < price_data['Price P/N'] , 'obv_signal'] = -1 #sell signal
    
    price_data.drop(['Price P/N',"OBV P/N"], axis = 1, inplace = True)
    return df

price_data = on_balance_volume(price_data)

In [53]:
### Keltner Channels ###

def keltner_channel(df, n=14):
    KelChM = pd.Series(((df['High'] + df['Low'] + df['Close']) / 3).rolling(n, min_periods=n).mean(),
                       name='KelChM_' + str(n))
    KelChU = pd.Series(((4 * df['High'] - 2 * df['Low'] + df['Close']) / 3).rolling(n, min_periods=n).mean(),
                       name='KelChU_' + str(n))
    KelChD = pd.Series(((-2 * df['High'] + 4 * df['Low'] + df['Close']) / 3).rolling(n, min_periods=n).mean(),
                       name='KelChD_' + str(n))
    df['KelChM'] = KelChM
    df['KelChU'] = KelChU
    df['KelChD'] = KelChD
    
    
    
    return df

price_data = keltner_channel(price_data)

In [54]:
def exponential_moving_average(df, n=14):
    
    EMA = pd.Series(df['Close'].ewm(span=n, min_periods=n).mean(), name='EMA_' + str(n))
    df['EMA'] = EMA
    
    return df

price_data = exponential_moving_average(price_data)

In [55]:
### Average True Range ###

def average_true_range(df, n=14):

    i = 0
    TR_l = [0]
    while i < df.index[-1]:
        TR = max(df.loc[i + 1, 'High'], df.loc[i, 'Close']) - min(df.loc[i + 1, 'Low'], df.loc[i, 'Close'])
        TR_l.append(TR)
        i = i + 1
    TR_s = pd.Series(TR_l)
    ATR = pd.Series(TR_s.ewm(span=n, min_periods=n).mean(), name='ATR')
    df['ATR'] = ATR
    
    #price_data = average_true_range(price_data, 14)
    price_data["Normalized ATR"]= (df["ATR"]/df["Close"])*100
    
    return df

price_data = average_true_range(price_data)

In [56]:
#Directional Movement Indicatiors ###

def average_directional_movement_index(df, n, n_ADX):

    i = 0
    UpI = []
    DoI = []
    while i + 1 <= df.index[-1]:
        UpMove = df.loc[i + 1, 'High'] - df.loc[i, 'High']
        DoMove = df.loc[i, 'Low'] - df.loc[i + 1, 'Low']
        if UpMove > DoMove and UpMove > 0:
            UpD = UpMove
        else:
            UpD = 0
        UpI.append(UpD)
        if DoMove > UpMove and DoMove > 0:
            DoD = DoMove
        else:
            DoD = 0
        DoI.append(DoD)
        i = i + 1
    i = 0
    TR_l = [0]
    while i < df.index[-1]:
        TR = max(df.loc[i + 1, 'High'], df.loc[i, 'Close']) - min(df.loc[i + 1, 'Low'], df.loc[i, 'Close'])
        TR_l.append(TR)
        i = i + 1
    TR_s = pd.Series(TR_l)
    ATR = pd.Series(TR_s.ewm(span=n, min_periods=n).mean())
    UpI = pd.Series(UpI)
    DoI = pd.Series(DoI)
    PosDI = pd.Series(UpI.ewm(span=n, min_periods=n).mean() / ATR)
    NegDI = pd.Series(DoI.ewm(span=n, min_periods=n).mean() / ATR)
    ADX = pd.Series((abs(PosDI - NegDI) / (PosDI + NegDI)).ewm(span=n_ADX, min_periods=n_ADX).mean()*100,
                    name='ADX_' + str(n) + '_' + str(n_ADX))
    df['ADX'] = ADX
    return df

price_data = average_directional_movement_index(price_data, 14, 2)

In [57]:
#### Importing final Data & Implementing all features ####

In [58]:
"""def function_call(price_data):
    print('rsd')
    price_data = rsi(price_data, price_index = 2)
    print('bbands')
    price_data = bbands(price_data, 2)
    print('volume raw')
    price_data = volume(price_data)
    print('aroon')
    price_data = aroon(price_data, high='High', low='Low')
    print('abands')
    price_data = abands(price_data, high='High', low='Low')
    print('stochastic')
    price_data = stochastic(price_data)
    print('chaikin')
    price_data = chaikin_money_flow(price_data)
    print('rate of change')
    price_data = rate_of_change(price_data)
    print('momentum')
    price_data = momentum(price_data)
    print('CCI')
    price_data = CCI(price_data)
    print('OBV')
    price_data = on_balance_volume(price_data)
    print('keltner')
    price_data = keltner_channel(price_data)
    print('exp mov avg')
    price_data = exponential_moving_average(price_data)
    print('atr')
    price_data = average_true_range(price_data)
    print('admi')
    price_data = average_directional_movement_index(price_data, 14, 2)
    return price_data"""

"def function_call(price_data):\n    print('rsd')\n    price_data = rsi(price_data, price_index = 2)\n    print('bbands')\n    price_data = bbands(price_data, 2)\n    print('volume raw')\n    price_data = volume(price_data)\n    print('aroon')\n    price_data = aroon(price_data, high='High', low='Low')\n    print('abands')\n    price_data = abands(price_data, high='High', low='Low')\n    print('stochastic')\n    price_data = stochastic(price_data)\n    print('chaikin')\n    price_data = chaikin_money_flow(price_data)\n    print('rate of change')\n    price_data = rate_of_change(price_data)\n    print('momentum')\n    price_data = momentum(price_data)\n    print('CCI')\n    price_data = CCI(price_data)\n    print('OBV')\n    price_data = on_balance_volume(price_data)\n    print('keltner')\n    price_data = keltner_channel(price_data)\n    print('exp mov avg')\n    price_data = exponential_moving_average(price_data)\n    print('atr')\n    price_data = average_true_range(price_data)\n    print('admi')\n    price_data = average_directional_movement_index(price_data, 14, 2)\n    return price_data"

In [59]:
"""function_call(input_df)"""

'function_call(input_df)'

In [60]:
price_data

,Date,Open,High,Low,Close,Adj Close,Volume,rsi,rsi_signal,bb_upper,...,OBV,OBV_ma,obv_signal,KelChM,KelChU,KelChD,EMA,ATR,Normalized ATR,ADX
0,2019-01-02,133.199997,136.500000,132.050003,136.000000,135.823837,6589,0.000000,1,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-03,133.500000,134.149994,126.750000,127.250000,127.085167,11750,0.000000,1,NaN,...,-11750,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-04,128.800003,133.600006,128.800003,133.250000,133.077393,3678,0.000000,1,NaN,...,3678,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-07,134.850006,137.500000,134.449997,137.149994,136.972336,5149,0.000000,1,NaN,...,5149,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-08,135.899994,139.350006,134.350006,138.800003,138.620209,4389,0.000000,1,NaN,...,4389,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2019-01-09,139.300003,145.199997,138.949997,144.000000,143.813477,9975,0.000000,1,NaN,...,9975,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2019-01-10,141.500000,142.449997,139.000000,141.750000,141.566391,4389,0.000000,1,NaN,...,-4389,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2019-01-11,142.949997,143.000000,139.500000,140.449997,140.268066,4934,0.000000,1,NaN,...,-4934,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2019-01-14,138.850006,139.000000,135.399994,136.850006,136.672745,3480,0.000000,1,NaN,...,-3480,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2019-01-15,137.550003,139.100006,135.949997,138.350006,138.170792,2822,0.000000,1,NaN,...,2822,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2019-01-16,138.300003,140.600006,137.300003,139.250000,139.069626,1694,0.000000,1,NaN,...,1694,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2019-01-17,139.000000,144.149994,138.300003,143.600006,143.414001,5613,0.000000,1,NaN,...,5613,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2019-01-18,145.000000,151.250000,144.300003,150.149994,149.955505,11328,0.000000,1,NaN,...,11328,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2019-01-21,151.000000,157.399994,150.250000,155.949997,155.747986,13859,58.360325,0,NaN,...,13859,2425.285714,0,139.557143,144.407143,134.707144,143.278913,5.455367,3.498151,NaN
14,2019-01-22,154.850006,157.699997,153.800003,155.050003,154.849167,11748,55.997042,0,NaN,...,-11748,1586.142857,0,141.033334,145.844047,136.222620,145.056133,5.220534,3.367000,76.839167
15,2019-01-23,156.500000,160.500000,155.350006,159.699997,159.493134,7949,55.662478,0,NaN,...,7949,2993.214286,0,143.114286,147.764285,138.464287,147.228746,5.254578,3.290280,82.040013
16,2019-01-24,161.500000,167.800003,160.649994,167.800003,167.582642,8177,49.895924,0,NaN,...,8177,3314.571429,0,145.509524,150.327381,140.691667,150.235574,5.670484,3.379311,84.669141
17,2019-01-25,168.300003,170.199997,164.199997,166.500000,166.284332,17937,48.531832,0,NaN,...,-17937,1665.571429,0,147.695238,152.723809,142.666667,152.582766,5.718038,3.434257,85.516546
18,2019-01-28,166.899994,170.199997,165.500000,166.500000,166.284332,6276,49.406133,0,NaN,...,0,1352.071429,1,149.830952,154.838094,144.823810,154.569409,5.572716,3.346976,81.426253
19,2019-01-29,167.949997,167.949997,164.850006,167.399994,167.183151,6642,51.161999,0,NaN,...,6642,1114.000000,0,151.546429,156.328570,146.764287,156.383855,5.223034,3.120092,56.163578
20,2019-01-30,166.800003,168.500000,130.000000,149.100006,148.906876,63537,48.487426,0,NaN,...,-63537,-3110.857143,0,152.127381,159.413094,144.841668,155.362063,9.891190,6.633930,47.752955
21,2019-01-31,151.300003,151.300003,143.050003,145.449997,145.261597,25115,30.480874,0,NaN,...,-25115,-4552.357143,1,152.528572,160.153571,144.903573,153.981175,9.662549,6.643210,64.559851
22,2019-02-01,145.500000,151.000000,101.500000,114.800003,114.651299,128455,34.879481,0,NaN,...,-128455,-13479.142857,0,151.482143,162.385713,140.578573,148.555145,15.179465,13.222530,70.161390
23,2019-02-04,126.500000,133.050003,115.750000,125.849998,125.686981,226422,28.197983,1,NaN,...,226422,2492.285714,0,150.559524,162.473808,138.645240,145.426925,15.602510,12.397704,71.453832
24,2019-02-05,128.000000,133.350006,124.650002,132.850006,132.677917,41298,27.360805,1,NaN,...,41298,5321.142857,-1,149.933334,162.233332,137.633335,143.701794,14.655718,11.031778,65.156488
25,2019-02-06,134.000000,136.600006,124.250000,130.350006,130.181168,37193,27.273622,1,NaN,...,-37193,2263.571429,0,149.103572,161.867857,136.339287,141.877370,14.340659,11.001656,70.303999
26,2019-02-07,130.500000,130.500000,105.000000,114.849998,114.701233,92993,25.030569,1,NaN,...,-92993,-5187.928571,0,146.833334,160.922619,132.744049,138.196459,15.860472,13.809728,76.410427
27,2019-02-08,113.400002,117.650002,86.300003,94.959999,94.836998,164250,19.815289,1,NaN,...,-164250,-17910.000000,0,142.912144,158.730001,127.094287,132.324786,17.964008,18.917447,78.445901
28,2019-02-11,97.000000,104.449997,95.919998,103.400002,103.266068,78538,20.321759,1,NaN,...,78538,-11461.000000,0,139.036429,155.185001,122.887858,128.406372,16.816041,16.263096,72.945510
29,2019-02-12,104.300003,107.599998,95.599998,102.000000,101.867874,52228,22.148059,1,177.657,...,-52228,-15759.357143,0,134.980477,151.618334,118.342619,124.836748,16.165007,15.848046,71.149563
30,2019-02-13,100.750000,101.500000,95.500000,100.599998,100.469688,49640,17.834131,1,179.765,...,-49640,-19889.142857,1,130.250715,146.806429,113.695001,121.566456,14.860897,14.772263,59.200770
31,2019-02-14,103.400002,106.599998,99.019997,102.300003,102.167488,34658,24.354938,1,181.002,...,34658,-16132.357143,0,125.655953,142.324524,108.987382,118.970958,13.880044,13.567980,55.358299
32,2019-02-15,102.000000,103.000000,98.820000,99.900002,99.770599,19381,25.439293,1,182.358,...,-19381,-17516.714286,0,120.882620,137.514049,104.251191,116.405344,12.575098,12.587686,27.950352
33,2019-02-18,106.000000,116.199997,104.000000,115.800003,115.650002,55639,35.858868,0,182.581,...,55639,-14016.928571,0,116.973096,134.254525,99.691667,116.324005,13.075609,11.291545,13.262623
34,2019-02-19,117.000000,125.800003,116.800003,121.449997,121.292679,60079,42.695858,0,182.440,...,60079,-5187.214286,0,114.983810,130.158097,99.809524,117.012068,12.662770,10.426324,5.485261
35,2019-02-20,123.099998,123.699997,113.199997,114.250000,114.102005,43942,46.714886,0,182.042,...,-43942,-6532.000000,0,112.873096,128.208096,97.538095,116.641647,12.372721,10.829515,11.170927
36,2019-02-21,114.250000,115.550003,106.849998,111.500000,111.355568,40334,43.640453,0,181.934,...,-40334,-237.642857,1,112.077858,124.498573,99.657142,115.952637,11.880556,10.655207,12.632927
37,2019-02-22,114.300003,115.800003,111.750000,115.550003,115.400330,18809,42.757492,0,181.702,...,18809,-15067.142857,0,111.326667,122.800954,99.852381,115.898718,10.865401,9.403203,5.601043
38,2019-02-25,117.050003,120.000000,114.750000,117.050003,116.898384,19693,45.246276,0,181.483,...,19693,-16610.357143,0,110.396905,121.624763,99.169047,116.052803,10.113848,8.640622,4.223867
39,2019-02-26,116.900002,118.099998,114.199997,117.000000,116.848450,6147,49.733131,0,181.252,...,-6147,-14392.785714,0,109.399286,120.023572,98.775000,116.179510,9.282620,7.933863,3.764809
40,2019-02-27,117.800003,118.050003,116.400002,117.900002,117.747284,7666,52.353719,0,180.900,...,7666,-7202.857143,0,109.446905,118.367620,100.526190,116.409560,8.262048,7.007674,4.156035
41,2019-02-28,116.699997,120.349998,116.500000,120.250000,120.094238,8688,53.658021,0,180.264,...,8688,5149.857143,0,110.832381,117.788810,103.875952,116.922878,7.672328,6.380314,7.524767
42,2019-03-01,121.000000,121.750000,118.500000,120.449997,120.293976,17122,58.834138,0,179.021,...,17122,763.000000,0,112.187857,118.767143,105.608571,117.394163,7.081428,5.879143,7.524767

In [37]:
#price_data.to_csv('./InputData/rnn_input.csv')
price_data.to_csv('./cnn_input/cnn_fullpriceinput.csv')